name = "change-notifier"
compatibility_date = "2025-03-05"
main = "./.output/server/index.mjs"
assets = { directory = "./.output/public/", binding = "ASSETS" }

[triggers]
# WARN: Make sure to have the same values in nitro config
crons = ["0 * * * *", "45 10 * * 2-6"]

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "STORAGE"
id = "f401b20a4bba4f07bdc8ea9270dd50ba"
